apiVersion: v1
kind: ConfigMap
metadata:
  name: construction-ai-config
  labels:
    app.kubernetes.io/name: construction-ai
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
