apiVersion: v1
kind: Secret
metadata:
  name: construction-ai-secrets
  labels:
    app.kubernetes.io/name: construction-ai
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
