apiVersion: v1
kind: Service
metadata:
  name: construction-ai-api
  labels:
    app.kubernetes.io/name: construction-ai
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: construction-ai
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
