[[permission]]
identifier = "allow-copy-last-log-lines"
description = "Enables the copy_last_log_lines command without any pre-configured scope."
commands.allow = ["copy_last_log_lines"]

[[permission]]
identifier = "deny-copy-last-log-lines"
description = "Denies the copy_last_log_lines command without any pre-configured scope."
commands.deny = ["copy_last_log_lines"]
