[[permission]]
identifier = "allow-get-api-url"
description = "Enables the get_api_url command without any pre-configured scope."
commands.allow = ["get_api_url"]

[[permission]]
identifier = "deny-get-api-url"
description = "Denies the get_api_url command without any pre-configured scope."
commands.deny = ["get_api_url"]
